Negative tests
HorizenLabs/poly-commit pull request #15
Opened 2021-05-27 21:34 UTC by phoinic

2021-05-28 08:02 UTC, DanieleDiBenedetto requested changes
Seems fine, I have still the doubt (as mentioned in the other PRs) regarding the need to generate fake proofs instead of modifying already existing ones, that lead you to the need of adding a separate setup_from_seed() function.

2021-06-08 05:47 UTC, phoinic commented on src/lib.rs
> +                    if is_negative {
Tests for different negative cases are added. I've covered 4 cases:
- wrong values
- wrong commitmnets
- wrong commiter key
- wrong verifier key

2021-06-08 08:16 UTC, DanieleDiBenedetto approved these changes

2021-06-18 08:13 UTC, DanieleDiBenedetto requested changes

2021-06-18 08:13 UTC, DanieleDiBenedetto commented on src/data_structures.rs
> +    fn copy_params(&mut self, other: &Self);
Let's specify it's used for testing purposes

2021-06-21 14:32 UTC, merged