Wrapping up possible crashes
HorizenLabs/poly-commit pull request #26
Opened 2021-07-24 15:26 UTC by phoinic

2021-07-26 09:54 UTC, DanieleDiBenedetto requested changes

2021-07-26 09:54 UTC, DanieleDiBenedetto commented on src/ipa_pc/mod.rs
> +    pub fn check_key(ck: &CommitterKey<G>, max_degree: usize) -> Result<bool, Error> {
setup returns a Result for the purpose of being generic in the trait. Here we know that we are in poly commit and the setup cannot fail, so the unwrap was ok. let's restore as it was before

2021-07-26 09:54 UTC, DanieleDiBenedetto commented on src/ipa_pc/mod.rs
> +                Err(Error::Other("Degree bound and shifted commitment are not synced".to_owned()))?
"Degree bound and shifted commitment must be both either present or not present"

2021-07-26 09:54 UTC, DanieleDiBenedetto commented on src/ipa_pc/mod.rs
> +        // TODO: check error message
"Hiding commitment and proof randomness must be both either present or not present"

2021-07-26 09:54 UTC, DanieleDiBenedetto commented on src/ipa_pc/mod.rs
> +                    "Labels ara not equal: poly '{}'. commitment '{}'",
typo ara -> are

2021-08-06 07:44 UTC, DanieleDiBenedetto approved these changes
Fine, remember to  remove the remainings TODO: Check error message

2021-08-30 11:39 UTC, phoinic reviewed
> Fine, remember to remove the remainings TODO: Check error message
Done

2021-10-06 13:24 UTC, merged